/* ============================================================
   kanji.js — JLPT N5 Kanji (103 characters)
   Format: { k, meaning_ru, meaning_en, on, kun, ex[] }
   ex: [ { w, r, ru, en } ]
   ============================================================ */

const KANJI_N5 = [
  // ── People ──────────────────────────────────────────────
  { k:'人', meaning_ru:'Человек',    meaning_en:'Person',
    on:'ジン・ニン', kun:'ひと',
    ex:[{w:'人',r:'ひと',ru:'Человек',en:'Person'},{w:'日本人',r:'にほんじん',ru:'Японец',en:'Japanese person'}] },
  { k:'男', meaning_ru:'Мужчина',    meaning_en:'Man',
    on:'ダン・ナン', kun:'おとこ',
    ex:[{w:'男の人',r:'おとこのひと',ru:'Мужчина',en:'Man'},{w:'男子',r:'だんし',ru:'Мальчик',en:'Boy'}] },
  { k:'女', meaning_ru:'Женщина',    meaning_en:'Woman',
    on:'ジョ・ニョ', kun:'おんな',
    ex:[{w:'女の人',r:'おんなのひと',ru:'Женщина',en:'Woman'},{w:'女子',r:'じょし',ru:'Девушка',en:'Girl'}] },
  { k:'子', meaning_ru:'Ребёнок',    meaning_en:'Child',
    on:'シ・ス', kun:'こ',
    ex:[{w:'子供',r:'こども',ru:'Ребёнок',en:'Child'},{w:'女の子',r:'おんなのこ',ru:'Девочка',en:'Girl'}] },
  { k:'友', meaning_ru:'Друг',       meaning_en:'Friend',
    on:'ユウ', kun:'とも',
    ex:[{w:'友達',r:'ともだち',ru:'Друг',en:'Friend'},{w:'友人',r:'ゆうじん',ru:'Друг (вежл.)',en:'Friend (formal)'}] },
  { k:'先', meaning_ru:'Раньше / Впереди', meaning_en:'Before / Ahead',
    on:'セン', kun:'さき',
    ex:[{w:'先生',r:'せんせい',ru:'Учитель',en:'Teacher'},{w:'先週',r:'せんしゅう',ru:'Прошлая неделя',en:'Last week'}] },
  { k:'生', meaning_ru:'Жить / Рождение', meaning_en:'Life / Birth',
    on:'セイ・ショウ', kun:'い・う・なま',
    ex:[{w:'先生',r:'せんせい',ru:'Учитель',en:'Teacher'},{w:'学生',r:'がくせい',ru:'Студент',en:'Student'}] },
  { k:'父', meaning_ru:'Отец',       meaning_en:'Father',
    on:'フ', kun:'ちち',
    ex:[{w:'父',r:'ちち',ru:'Отец',en:'Father'},{w:'お父さん',r:'おとうさん',ru:'Папа',en:'Dad'}] },
  { k:'母', meaning_ru:'Мать',       meaning_en:'Mother',
    on:'ボ', kun:'はは',
    ex:[{w:'母',r:'はは',ru:'Мать',en:'Mother'},{w:'お母さん',r:'おかあさん',ru:'Мама',en:'Mom'}] },

  // ── Numbers ─────────────────────────────────────────────
  { k:'一', meaning_ru:'Один',   meaning_en:'One',
    on:'イチ・イツ', kun:'ひと',
    ex:[{w:'一つ',r:'ひとつ',ru:'Одна штука',en:'One thing'},{w:'一月',r:'いちがつ',ru:'Январь',en:'January'}] },
  { k:'二', meaning_ru:'Два',    meaning_en:'Two',
    on:'ニ', kun:'ふた',
    ex:[{w:'二つ',r:'ふたつ',ru:'Две штуки',en:'Two things'},{w:'二月',r:'にがつ',ru:'Февраль',en:'February'}] },
  { k:'三', meaning_ru:'Три',    meaning_en:'Three',
    on:'サン', kun:'み',
    ex:[{w:'三つ',r:'みっつ',ru:'Три штуки',en:'Three things'},{w:'三月',r:'さんがつ',ru:'Март',en:'March'}] },
  { k:'四', meaning_ru:'Четыре', meaning_en:'Four',
    on:'シ', kun:'よ・よん',
    ex:[{w:'四つ',r:'よっつ',ru:'Четыре штуки',en:'Four things'},{w:'四月',r:'しがつ',ru:'Апрель',en:'April'}] },
  { k:'五', meaning_ru:'Пять',   meaning_en:'Five',
    on:'ゴ', kun:'いつ',
    ex:[{w:'五つ',r:'いつつ',ru:'Пять штук',en:'Five things'},{w:'五月',r:'ごがつ',ru:'Май',en:'May'}] },
  { k:'六', meaning_ru:'Шесть',  meaning_en:'Six',
    on:'ロク', kun:'む',
    ex:[{w:'六つ',r:'むっつ',ru:'Шесть штук',en:'Six things'},{w:'六月',r:'ろくがつ',ru:'Июнь',en:'June'}] },
  { k:'七', meaning_ru:'Семь',   meaning_en:'Seven',
    on:'シチ', kun:'なな',
    ex:[{w:'七つ',r:'ななつ',ru:'Семь штук',en:'Seven things'},{w:'七月',r:'しちがつ',ru:'Июль',en:'July'}] },
  { k:'八', meaning_ru:'Восемь', meaning_en:'Eight',
    on:'ハチ', kun:'や',
    ex:[{w:'八つ',r:'やっつ',ru:'Восемь штук',en:'Eight things'},{w:'八月',r:'はちがつ',ru:'Август',en:'August'}] },
  { k:'九', meaning_ru:'Девять', meaning_en:'Nine',
    on:'ク・キュウ', kun:'ここの',
    ex:[{w:'九つ',r:'ここのつ',ru:'Девять штук',en:'Nine things'},{w:'九月',r:'くがつ',ru:'Сентябрь',en:'September'}] },
  { k:'十', meaning_ru:'Десять', meaning_en:'Ten',
    on:'ジュウ', kun:'とお',
    ex:[{w:'十',r:'じゅう',ru:'Десять',en:'Ten'},{w:'十月',r:'じゅうがつ',ru:'Октябрь',en:'October'}] },
  { k:'百', meaning_ru:'Сто',       meaning_en:'Hundred',
    on:'ヒャク', kun:'-',
    ex:[{w:'百',r:'ひゃく',ru:'Сто',en:'Hundred'},{w:'三百',r:'さんびゃく',ru:'Триста',en:'Three hundred'}] },
  { k:'千', meaning_ru:'Тысяча',    meaning_en:'Thousand',
    on:'セン', kun:'ち',
    ex:[{w:'千',r:'せん',ru:'Тысяча',en:'Thousand'},{w:'三千',r:'さんぜん',ru:'Три тысячи',en:'Three thousand'}] },
  { k:'万', meaning_ru:'Десять тысяч', meaning_en:'Ten thousand',
    on:'マン・バン', kun:'-',
    ex:[{w:'一万',r:'いちまん',ru:'10 000',en:'Ten thousand'},{w:'万年',r:'まんねん',ru:'Вечность',en:'Ten thousand years'}] },
  { k:'円', meaning_ru:'Йена / Круг', meaning_en:'Yen / Circle',
    on:'エン', kun:'まる',
    ex:[{w:'百円',r:'ひゃくえん',ru:'100 йен',en:'100 yen'},{w:'円い',r:'まるい',ru:'Круглый',en:'Round'}] },

  // ── Time ────────────────────────────────────────────────
  { k:'日', meaning_ru:'День / Солнце / Япония', meaning_en:'Day / Sun / Japan',
    on:'ニチ・ジツ', kun:'ひ・か',
    ex:[{w:'今日',r:'きょう',ru:'Сегодня',en:'Today'},{w:'日曜日',r:'にちようび',ru:'Воскресенье',en:'Sunday'}] },
  { k:'月', meaning_ru:'Луна / Месяц', meaning_en:'Moon / Month',
    on:'ゲツ・ガツ', kun:'つき',
    ex:[{w:'月曜日',r:'げつようび',ru:'Понедельник',en:'Monday'},{w:'三月',r:'さんがつ',ru:'Март',en:'March'}] },
  { k:'年', meaning_ru:'Год',          meaning_en:'Year',
    on:'ネン', kun:'とし',
    ex:[{w:'今年',r:'ことし',ru:'Этот год',en:'This year'},{w:'来年',r:'らいねん',ru:'Следующий год',en:'Next year'}] },
  { k:'時', meaning_ru:'Время / Час',  meaning_en:'Time / Hour',
    on:'ジ', kun:'とき',
    ex:[{w:'何時',r:'なんじ',ru:'Который час',en:'What time'},{w:'三時',r:'さんじ',ru:'Три часа',en:'Three o\'clock'}] },
  { k:'分', meaning_ru:'Минута / Часть', meaning_en:'Minute / Part',
    on:'フン・プン・ブン', kun:'わ',
    ex:[{w:'五分',r:'ごふん',ru:'Пять минут',en:'Five minutes'},{w:'自分',r:'じぶん',ru:'Сам / Себя',en:'Oneself'}] },
  { k:'半', meaning_ru:'Половина',    meaning_en:'Half',
    on:'ハン', kun:'なか',
    ex:[{w:'三時半',r:'さんじはん',ru:'Полчетвёртого',en:'Half past three'},{w:'半分',r:'はんぶん',ru:'Половина',en:'Half'}] },
  { k:'今', meaning_ru:'Сейчас',      meaning_en:'Now',
    on:'コン・キン', kun:'いま',
    ex:[{w:'今',r:'いま',ru:'Сейчас',en:'Now'},{w:'今日',r:'きょう',ru:'Сегодня',en:'Today'}] },
  { k:'週', meaning_ru:'Неделя',      meaning_en:'Week',
    on:'シュウ', kun:'-',
    ex:[{w:'今週',r:'こんしゅう',ru:'Эта неделя',en:'This week'},{w:'来週',r:'らいしゅう',ru:'Следующая неделя',en:'Next week'}] },

  // ── Days of week (elements) ───────────────────────────
  { k:'火', meaning_ru:'Огонь',  meaning_en:'Fire',
    on:'カ', kun:'ひ',
    ex:[{w:'火曜日',r:'かようび',ru:'Вторник',en:'Tuesday'},{w:'火',r:'ひ',ru:'Огонь',en:'Fire'}] },
  { k:'水', meaning_ru:'Вода',   meaning_en:'Water',
    on:'スイ', kun:'みず',
    ex:[{w:'水曜日',r:'すいようび',ru:'Среда',en:'Wednesday'},{w:'水',r:'みず',ru:'Вода',en:'Water'}] },
  { k:'木', meaning_ru:'Дерево', meaning_en:'Tree / Wood',
    on:'モク・ボク', kun:'き',
    ex:[{w:'木曜日',r:'もくようび',ru:'Четверг',en:'Thursday'},{w:'木',r:'き',ru:'Дерево',en:'Tree'}] },
  { k:'金', meaning_ru:'Золото / Деньги', meaning_en:'Gold / Money',
    on:'キン・コン', kun:'かね',
    ex:[{w:'金曜日',r:'きんようび',ru:'Пятница',en:'Friday'},{w:'お金',r:'おかね',ru:'Деньги',en:'Money'}] },
  { k:'土', meaning_ru:'Земля / Почва',   meaning_en:'Earth / Soil',
    on:'ド・ト', kun:'つち',
    ex:[{w:'土曜日',r:'どようび',ru:'Суббота',en:'Saturday'},{w:'土',r:'つち',ru:'Земля',en:'Soil'}] },

  // ── Directions & places ──────────────────────────────
  { k:'上', meaning_ru:'Вверх / На',      meaning_en:'Up / Above',
    on:'ジョウ・ショウ', kun:'うえ・あ',
    ex:[{w:'上',r:'うえ',ru:'Вверху',en:'Above'},{w:'上手',r:'じょうず',ru:'Умелый',en:'Skilled'}] },
  { k:'下', meaning_ru:'Вниз / Под',      meaning_en:'Down / Below',
    on:'カ・ゲ', kun:'した・くだ',
    ex:[{w:'下',r:'した',ru:'Внизу',en:'Below'},{w:'地下',r:'ちか',ru:'Подземный',en:'Underground'}] },
  { k:'中', meaning_ru:'Середина / Внутри', meaning_en:'Middle / Inside',
    on:'チュウ', kun:'なか',
    ex:[{w:'中',r:'なか',ru:'Внутри',en:'Inside'},{w:'中国',r:'ちゅうごく',ru:'Китай',en:'China'}] },
  { k:'外', meaning_ru:'Снаружи',         meaning_en:'Outside',
    on:'ガイ・ゲ', kun:'そと',
    ex:[{w:'外',r:'そと',ru:'Снаружи',en:'Outside'},{w:'外国',r:'がいこく',ru:'Заграница',en:'Foreign country'}] },
  { k:'右', meaning_ru:'Правый',          meaning_en:'Right',
    on:'ウ・ユウ', kun:'みぎ',
    ex:[{w:'右',r:'みぎ',ru:'Справа',en:'Right'},{w:'右手',r:'みぎて',ru:'Правая рука',en:'Right hand'}] },
  { k:'左', meaning_ru:'Левый',           meaning_en:'Left',
    on:'サ', kun:'ひだり',
    ex:[{w:'左',r:'ひだり',ru:'Слева',en:'Left'},{w:'左手',r:'ひだりて',ru:'Левая рука',en:'Left hand'}] },
  { k:'東', meaning_ru:'Восток',          meaning_en:'East',
    on:'トウ', kun:'ひがし',
    ex:[{w:'東',r:'ひがし',ru:'Восток',en:'East'},{w:'東京',r:'とうきょう',ru:'Токио',en:'Tokyo'}] },
  { k:'西', meaning_ru:'Запад',           meaning_en:'West',
    on:'セイ・サイ', kun:'にし',
    ex:[{w:'西',r:'にし',ru:'Запад',en:'West'},{w:'関西',r:'かんさい',ru:'Кансай',en:'Kansai'}] },
  { k:'南', meaning_ru:'Юг',              meaning_en:'South',
    on:'ナン・ナ', kun:'みなみ',
    ex:[{w:'南',r:'みなみ',ru:'Юг',en:'South'},{w:'南口',r:'みなみぐち',ru:'Южный выход',en:'South exit'}] },
  { k:'北', meaning_ru:'Север',           meaning_en:'North',
    on:'ホク', kun:'きた',
    ex:[{w:'北',r:'きた',ru:'Север',en:'North'},{w:'北海道',r:'ほっかいどう',ru:'Хоккайдо',en:'Hokkaido'}] },

  // ── Nature ──────────────────────────────────────────────
  { k:'山', meaning_ru:'Гора',   meaning_en:'Mountain',
    on:'サン', kun:'やま',
    ex:[{w:'山',r:'やま',ru:'Гора',en:'Mountain'},{w:'富士山',r:'ふじさん',ru:'Фудзи',en:'Mt. Fuji'}] },
  { k:'川', meaning_ru:'Река',   meaning_en:'River',
    on:'セン', kun:'かわ',
    ex:[{w:'川',r:'かわ',ru:'Река',en:'River'},{w:'川口',r:'かわぐち',ru:'Кавагути',en:'Kawaguchi'}] },
  { k:'田', meaning_ru:'Рисовое поле', meaning_en:'Rice field',
    on:'デン', kun:'た',
    ex:[{w:'田んぼ',r:'たんぼ',ru:'Поле риса',en:'Rice paddy'},{w:'田中',r:'たなか',ru:'Танака',en:'Tanaka (surname)'}] },
  { k:'空', meaning_ru:'Небо / Пустой', meaning_en:'Sky / Empty',
    on:'クウ', kun:'そら・から',
    ex:[{w:'空',r:'そら',ru:'Небо',en:'Sky'},{w:'空港',r:'くうこう',ru:'Аэропорт',en:'Airport'}] },
  { k:'雨', meaning_ru:'Дождь',  meaning_en:'Rain',
    on:'ウ', kun:'あめ',
    ex:[{w:'雨',r:'あめ',ru:'Дождь',en:'Rain'},{w:'大雨',r:'おおあめ',ru:'Ливень',en:'Heavy rain'}] },

  // ── Places & buildings ──────────────────────────────────
  { k:'国', meaning_ru:'Страна',  meaning_en:'Country',
    on:'コク', kun:'くに',
    ex:[{w:'国',r:'くに',ru:'Страна',en:'Country'},{w:'外国',r:'がいこく',ru:'Заграница',en:'Abroad'}] },
  { k:'校', meaning_ru:'Школа',   meaning_en:'School',
    on:'コウ', kun:'-',
    ex:[{w:'学校',r:'がっこう',ru:'Школа',en:'School'},{w:'高校',r:'こうこう',ru:'Старшая школа',en:'High school'}] },
  { k:'学', meaning_ru:'Учёба',   meaning_en:'Study / Learning',
    on:'ガク・ガッ', kun:'まな',
    ex:[{w:'大学',r:'だいがく',ru:'Университет',en:'University'},{w:'学生',r:'がくせい',ru:'Студент',en:'Student'}] },
  { k:'店', meaning_ru:'Магазин', meaning_en:'Shop',
    on:'テン', kun:'みせ',
    ex:[{w:'お店',r:'おみせ',ru:'Магазин',en:'Shop'},{w:'本屋',r:'ほんや',ru:'Книжный',en:'Bookstore'}] },
  { k:'駅', meaning_ru:'Станция', meaning_en:'Station',
    on:'エキ', kun:'-',
    ex:[{w:'駅',r:'えき',ru:'Станция',en:'Station'},{w:'東京駅',r:'とうきょうえき',ru:'Ст. Токио',en:'Tokyo station'}] },
  { k:'道', meaning_ru:'Дорога',  meaning_en:'Road / Way',
    on:'ドウ・トウ', kun:'みち',
    ex:[{w:'道',r:'みち',ru:'Дорога',en:'Road'},{w:'北海道',r:'ほっかいどう',ru:'Хоккайдо',en:'Hokkaido'}] },

  // ── Body ─────────────────────────────────────────────────
  { k:'口', meaning_ru:'Рот / Вход',      meaning_en:'Mouth / Opening',
    on:'コウ・ク', kun:'くち',
    ex:[{w:'口',r:'くち',ru:'Рот',en:'Mouth'},{w:'入口',r:'いりぐち',ru:'Вход',en:'Entrance'}] },
  { k:'目', meaning_ru:'Глаз',            meaning_en:'Eye',
    on:'モク・ボク', kun:'め',
    ex:[{w:'目',r:'め',ru:'Глаз',en:'Eye'},{w:'目的',r:'もくてき',ru:'Цель',en:'Goal'}] },
  { k:'耳', meaning_ru:'Ухо',             meaning_en:'Ear',
    on:'ジ', kun:'みみ',
    ex:[{w:'耳',r:'みみ',ru:'Ухо',en:'Ear'},{w:'耳鼻科',r:'じびか',ru:'ЛОР',en:'ENT clinic'}] },
  { k:'手', meaning_ru:'Рука',            meaning_en:'Hand',
    on:'シュ', kun:'て',
    ex:[{w:'手',r:'て',ru:'Рука',en:'Hand'},{w:'上手',r:'じょうず',ru:'Умелый',en:'Skilled'}] },
  { k:'足', meaning_ru:'Нога / Хватать',  meaning_en:'Foot / Enough',
    on:'ソク', kun:'あし・た',
    ex:[{w:'足',r:'あし',ru:'Нога',en:'Leg'},{w:'足りる',r:'たりる',ru:'Хватать',en:'To be enough'}] },

  // ── Verbs (kanji used in common verbs) ───────────────────
  { k:'行', meaning_ru:'Идти',            meaning_en:'To go',
    on:'コウ・ギョウ', kun:'い・ゆ',
    ex:[{w:'行く',r:'いく',ru:'Идти',en:'To go'},{w:'銀行',r:'ぎんこう',ru:'Банк',en:'Bank'}] },
  { k:'来', meaning_ru:'Прийти',          meaning_en:'To come',
    on:'ライ', kun:'く・き',
    ex:[{w:'来る',r:'くる',ru:'Прийти',en:'To come'},{w:'来年',r:'らいねん',ru:'Следующий год',en:'Next year'}] },
  { k:'帰', meaning_ru:'Вернуться',       meaning_en:'To return',
    on:'キ', kun:'かえ',
    ex:[{w:'帰る',r:'かえる',ru:'Вернуться',en:'To return'},{w:'帰国',r:'きこく',ru:'Возвращение',en:'Return home'}] },
  { k:'食', meaning_ru:'Еда / Есть',      meaning_en:'Eat / Food',
    on:'ショク', kun:'た・く',
    ex:[{w:'食べる',r:'たべる',ru:'Есть',en:'To eat'},{w:'食堂',r:'しょくどう',ru:'Столовая',en:'Cafeteria'}] },
  { k:'飲', meaning_ru:'Пить',            meaning_en:'To drink',
    on:'イン', kun:'の',
    ex:[{w:'飲む',r:'のむ',ru:'Пить',en:'To drink'},{w:'飲み物',r:'のみもの',ru:'Напиток',en:'Drink'}] },
  { k:'見', meaning_ru:'Смотреть',        meaning_en:'To see / look',
    on:'ケン', kun:'み',
    ex:[{w:'見る',r:'みる',ru:'Смотреть',en:'To look'},{w:'見学',r:'けんがく',ru:'Экскурсия',en:'Field trip'}] },
  { k:'聞', meaning_ru:'Слышать',         meaning_en:'To hear / listen',
    on:'ブン・モン', kun:'き',
    ex:[{w:'聞く',r:'きく',ru:'Слушать',en:'To listen'},{w:'新聞',r:'しんぶん',ru:'Газета',en:'Newspaper'}] },
  { k:'書', meaning_ru:'Писать',          meaning_en:'To write',
    on:'ショ', kun:'か',
    ex:[{w:'書く',r:'かく',ru:'Писать',en:'To write'},{w:'教科書',r:'きょうかしょ',ru:'Учебник',en:'Textbook'}] },
  { k:'読', meaning_ru:'Читать',          meaning_en:'To read',
    on:'ドク・トク', kun:'よ',
    ex:[{w:'読む',r:'よむ',ru:'Читать',en:'To read'},{w:'読書',r:'どくしょ',ru:'Чтение',en:'Reading'}] },
  { k:'話', meaning_ru:'Говорить / Рассказ', meaning_en:'Speak / Story',
    on:'ワ', kun:'はな・はなし',
    ex:[{w:'話す',r:'はなす',ru:'Говорить',en:'To speak'},{w:'電話',r:'でんわ',ru:'Телефон',en:'Telephone'}] },
  { k:'買', meaning_ru:'Покупать',        meaning_en:'To buy',
    on:'バイ', kun:'か',
    ex:[{w:'買う',r:'かう',ru:'Покупать',en:'To buy'},{w:'買い物',r:'かいもの',ru:'Покупки',en:'Shopping'}] },
  { k:'出', meaning_ru:'Выходить',        meaning_en:'Exit / Put out',
    on:'シュツ', kun:'で・だ',
    ex:[{w:'出る',r:'でる',ru:'Выходить',en:'To exit'},{w:'出口',r:'でぐち',ru:'Выход',en:'Exit'}] },
  { k:'入', meaning_ru:'Входить',         meaning_en:'Enter',
    on:'ニュウ', kun:'い・はい',
    ex:[{w:'入る',r:'はいる',ru:'Входить',en:'To enter'},{w:'入口',r:'いりぐち',ru:'Вход',en:'Entrance'}] },
  { k:'休', meaning_ru:'Отдыхать',        meaning_en:'Rest',
    on:'キュウ', kun:'やす',
    ex:[{w:'休む',r:'やすむ',ru:'Отдыхать',en:'To rest'},{w:'休日',r:'きゅうじつ',ru:'Выходной',en:'Holiday'}] },
  { k:'起', meaning_ru:'Просыпаться',     meaning_en:'To rise / wake up',
    on:'キ', kun:'お',
    ex:[{w:'起きる',r:'おきる',ru:'Просыпаться',en:'To wake up'},{w:'起立',r:'きりつ',ru:'Встать',en:'Stand up'}] },
  { k:'寝', meaning_ru:'Спать',           meaning_en:'To sleep',
    on:'シン', kun:'ね',
    ex:[{w:'寝る',r:'ねる',ru:'Спать',en:'To sleep'},{w:'寝室',r:'しんしつ',ru:'Спальня',en:'Bedroom'}] },
  { k:'待', meaning_ru:'Ждать',           meaning_en:'To wait',
    on:'タイ', kun:'ま',
    ex:[{w:'待つ',r:'まつ',ru:'Ждать',en:'To wait'},{w:'待合室',r:'まちあいしつ',ru:'Зал ожидания',en:'Waiting room'}] },
  { k:'会', meaning_ru:'Встречаться',     meaning_en:'Meet / Association',
    on:'カイ・エ', kun:'あ',
    ex:[{w:'会う',r:'あう',ru:'Встречаться',en:'To meet'},{w:'会社',r:'かいしゃ',ru:'Компания',en:'Company'}] },
  { k:'言', meaning_ru:'Говорить',        meaning_en:'Say',
    on:'ゲン・ゴン', kun:'い・こと',
    ex:[{w:'言う',r:'いう',ru:'Говорить',en:'To say'},{w:'言葉',r:'ことば',ru:'Слово',en:'Word'}] },
  { k:'立', meaning_ru:'Стоять',          meaning_en:'Stand',
    on:'リツ・リュウ', kun:'た',
    ex:[{w:'立つ',r:'たつ',ru:'Стоять',en:'To stand'},{w:'起立',r:'きりつ',ru:'Встать',en:'Stand up'}] },

  // ── Adjectives & qualities ─────────────────────────────
  { k:'大', meaning_ru:'Большой',         meaning_en:'Big / Large',
    on:'ダイ・タイ', kun:'おお',
    ex:[{w:'大きい',r:'おおきい',ru:'Большой',en:'Big'},{w:'大学',r:'だいがく',ru:'Университет',en:'University'}] },
  { k:'小', meaning_ru:'Маленький',       meaning_en:'Small',
    on:'ショウ', kun:'ちい・こ',
    ex:[{w:'小さい',r:'ちいさい',ru:'Маленький',en:'Small'},{w:'小学校',r:'しょうがっこう',ru:'Нач. школа',en:'Elementary school'}] },
  { k:'新', meaning_ru:'Новый',           meaning_en:'New',
    on:'シン', kun:'あたら',
    ex:[{w:'新しい',r:'あたらしい',ru:'Новый',en:'New'},{w:'新聞',r:'しんぶん',ru:'Газета',en:'Newspaper'}] },
  { k:'古', meaning_ru:'Старый',          meaning_en:'Old',
    on:'コ', kun:'ふる',
    ex:[{w:'古い',r:'ふるい',ru:'Старый',en:'Old'},{w:'古本',r:'ふるほん',ru:'Старая книга',en:'Used book'}] },
  { k:'高', meaning_ru:'Высокий / Дорогой', meaning_en:'High / Expensive',
    on:'コウ', kun:'たか',
    ex:[{w:'高い',r:'たかい',ru:'Высокий',en:'Tall/Expensive'},{w:'高校',r:'こうこう',ru:'Ст. школа',en:'High school'}] },
  { k:'長', meaning_ru:'Длинный',         meaning_en:'Long',
    on:'チョウ', kun:'なが',
    ex:[{w:'長い',r:'ながい',ru:'Длинный',en:'Long'},{w:'社長',r:'しゃちょう',ru:'Директор',en:'President'}] },
  { k:'多', meaning_ru:'Много',           meaning_en:'Many',
    on:'タ', kun:'おお',
    ex:[{w:'多い',r:'おおい',ru:'Много',en:'Many'},{w:'多分',r:'たぶん',ru:'Наверное',en:'Probably'}] },
  { k:'少', meaning_ru:'Мало',            meaning_en:'Few',
    on:'ショウ', kun:'すく・すこ',
    ex:[{w:'少ない',r:'すくない',ru:'Мало',en:'Few'},{w:'少し',r:'すこし',ru:'Немного',en:'A little'}] },
  { k:'好', meaning_ru:'Нравиться',       meaning_en:'Like',
    on:'コウ', kun:'す・この',
    ex:[{w:'好き',r:'すき',ru:'Нравится',en:'Like'},{w:'大好き',r:'だいすき',ru:'Очень нравится',en:'Love'}] },
  { k:'白', meaning_ru:'Белый',           meaning_en:'White',
    on:'ハク', kun:'しろ',
    ex:[{w:'白い',r:'しろい',ru:'Белый',en:'White'},{w:'白黒',r:'しろくろ',ru:'Ч/б',en:'Black & white'}] },
  { k:'黒', meaning_ru:'Чёрный',          meaning_en:'Black',
    on:'コク', kun:'くろ',
    ex:[{w:'黒い',r:'くろい',ru:'Чёрный',en:'Black'},{w:'黒板',r:'こくばん',ru:'Доска',en:'Blackboard'}] },
  { k:'赤', meaning_ru:'Красный',         meaning_en:'Red',
    on:'セキ', kun:'あか',
    ex:[{w:'赤い',r:'あかい',ru:'Красный',en:'Red'},{w:'赤ちゃん',r:'あかちゃん',ru:'Младенец',en:'Baby'}] },
  { k:'青', meaning_ru:'Синий / Зелёный', meaning_en:'Blue / Green',
    on:'セイ・ショウ', kun:'あお',
    ex:[{w:'青い',r:'あおい',ru:'Синий',en:'Blue'},{w:'青空',r:'あおぞら',ru:'Голубое небо',en:'Blue sky'}] },

  // ── Common nouns & study ────────────────────────────────
  { k:'本', meaning_ru:'Книга / Основной', meaning_en:'Book / Origin',
    on:'ホン', kun:'もと',
    ex:[{w:'本',r:'ほん',ru:'Книга',en:'Book'},{w:'日本',r:'にほん',ru:'Япония',en:'Japan'}] },
  { k:'語', meaning_ru:'Язык / Слово',    meaning_en:'Language / Word',
    on:'ゴ', kun:'かた',
    ex:[{w:'日本語',r:'にほんご',ru:'Японский',en:'Japanese'},{w:'英語',r:'えいご',ru:'Английский',en:'English'}] },
  { k:'何', meaning_ru:'Что / Сколько',   meaning_en:'What / How many',
    on:'カ', kun:'なに・なん',
    ex:[{w:'何',r:'なに',ru:'Что',en:'What'},{w:'何時',r:'なんじ',ru:'Который час',en:'What time'}] },
  { k:'名', meaning_ru:'Имя',             meaning_en:'Name',
    on:'メイ・ミョウ', kun:'な',
    ex:[{w:'名前',r:'なまえ',ru:'Имя',en:'Name'},{w:'有名',r:'ゆうめい',ru:'Известный',en:'Famous'}] },
  { k:'電', meaning_ru:'Электричество',   meaning_en:'Electricity',
    on:'デン', kun:'-',
    ex:[{w:'電車',r:'でんしゃ',ru:'Поезд',en:'Train'},{w:'電話',r:'でんわ',ru:'Телефон',en:'Telephone'}] },
  { k:'車', meaning_ru:'Автомобиль',      meaning_en:'Car / Wheel',
    on:'シャ', kun:'くるま',
    ex:[{w:'車',r:'くるま',ru:'Машина',en:'Car'},{w:'電車',r:'でんしゃ',ru:'Поезд',en:'Train'}] },
  { k:'花', meaning_ru:'Цветок',          meaning_en:'Flower',
    on:'カ・ケ', kun:'はな',
    ex:[{w:'花',r:'はな',ru:'Цветок',en:'Flower'},{w:'花火',r:'はなび',ru:'Фейерверк',en:'Fireworks'}] },
  { k:'魚', meaning_ru:'Рыба',            meaning_en:'Fish',
    on:'ギョ', kun:'さかな',
    ex:[{w:'魚',r:'さかな',ru:'Рыба',en:'Fish'},{w:'金魚',r:'きんぎょ',ru:'Золотая рыбка',en:'Goldfish'}] },
  { k:'肉', meaning_ru:'Мясо',            meaning_en:'Meat',
    on:'ニク', kun:'-',
    ex:[{w:'肉',r:'にく',ru:'Мясо',en:'Meat'},{w:'牛肉',r:'ぎゅうにく',ru:'Говядина',en:'Beef'}] },
  { k:'勉', meaning_ru:'Усердие',         meaning_en:'Diligence',
    on:'ベン', kun:'-',
    ex:[{w:'勉強',r:'べんきょう',ru:'Учёба',en:'Study'},{w:'勉強する',r:'べんきょうする',ru:'Учиться',en:'To study'}] },
  { k:'強', meaning_ru:'Сильный',         meaning_en:'Strong',
    on:'キョウ', kun:'つよ',
    ex:[{w:'強い',r:'つよい',ru:'Сильный',en:'Strong'},{w:'勉強',r:'べんきょう',ru:'Учёба',en:'Study'}] },
  { k:'英', meaning_ru:'Английский',      meaning_en:'England / English',
    on:'エイ', kun:'-',
    ex:[{w:'英語',r:'えいご',ru:'Английский',en:'English'},{w:'英国',r:'えいこく',ru:'Великобритания',en:'UK'}] },
  { k:'仕', meaning_ru:'Служить',         meaning_en:'Serve',
    on:'シ・ジ', kun:'-',
    ex:[{w:'仕事',r:'しごと',ru:'Работа',en:'Work'},{w:'仕方',r:'しかた',ru:'Способ',en:'Way / Method'}] },
  { k:'事', meaning_ru:'Дело / Вещь',     meaning_en:'Thing / Matter',
    on:'ジ・ズ', kun:'こと',
    ex:[{w:'仕事',r:'しごと',ru:'Работа',en:'Work'},{w:'大事',r:'だいじ',ru:'Важный',en:'Important'}] },
];
